db.url=jdbc:mysql://rm-wz959t478klg1820ego.mysql.rds.aliyuncs.com:3306/ai_platform_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
db.username=platform
db.password=Platform2025
db.schema=ai_platform
